apiVersion: v1
kind: Template
metadata:
  name: graph-sync-scheduler-buildconfig
  annotations:
    description: >
      This is Thoth Graph Sync Scheduler BuildConfig, this template is meant to
      be used by Bots, but could also be used by humans...
    openshift.io/display-name: "Thoth Core: Graph Sync Scheduler BuildConfig"
    version: 0.1.0
    tags: thoth,graph-sync-scheduler,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Thoth Graph Sync Scheduler BuildConfig, this template is meant to
      be used by Bots, but could also be used by humans...
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    template: graph-sync-scheduler-buildconfig
    app: thoth
    component: graph-sync-scheduler

parameters:
  - description: Name of the github repository for Thoth's Graph Sync Scheduler
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: "https://github.com/thoth-station/graph-sync-scheduler"

  - description: Git reference to be used for Thoth's Graph Sync Scheduler
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: "master"

  - description: >
      Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: graph-sync-scheduler
      labels:
        app: thoth
        component: graph-sync-scheduler
    spec:
      successfulBuildsHistoryLimit: 1
      failedBuildsHistoryLimit: 2
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 512Mi
      output:
        to:
          kind: ImageStreamTag
          name: "graph-sync-scheduler:${IMAGE_STREAM_TAG}"
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python-36-centos7:latest
          env:
            - name: ENABLE_PIPENV
              value: "1"
            - name: UPGRADE_PIP_TO_LATEST
              value: ""
            - name: "THOTH_DRY_RUN"
              value: "1"
            - name: "THOTH_ADVISE"
              value: "1"
            - name: "THAMOS_VERBOSE"
              value: "1"
            - name: "THAMOS_DEBUG"
              value: "1"
            - name: "THAMOS_CONFIG_TEMPLATE"
              value: ".thoth_template.yaml"
            - name: "THAMOS_CONFIG_EXPAND_ENV"
              value: "1"
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: "Generic"
          generic:
            secretReference:
              name: generic-webhook-secret
